In [2]:
nums = (1,2,3,4,5,6)
total = 0
cnt = 0
for i in nums:
    total += i
    cnt += 1
average = total / cnt
print(average)

3.5


### Установка NumPy

In [3]:
import numpy as np

In [4]:
print(np.__version__)

2.1.3


In [3]:
#pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
#pip install --force-reinstall numpy==2.0.1

In [5]:
#pip install numpy --upgrade

### Создание массива

In [6]:
# 1D
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [7]:
type(a)

numpy.ndarray

In [8]:
# 2D
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
# 3D
a = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [14]:
np.empty(3)

array([7.74860419e-304, 7.74860419e-304, 7.74860419e-304])

$7.74860419e-304 \approx 7.7486 \cdot 10^{-304}= 0.000....0077484$

In [15]:
np.empty([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.arange(4)

array([0, 1, 2, 3])

In [17]:
np.arange(1,4)

array([1, 2, 3])

In [20]:
np.arange(1,10,3)

array([1, 4, 7])

In [24]:
np.linspace(0, 10, num = 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Атрибуты

In [28]:
l = [1,2,3,4]
l.append(5)

l.sort()
l

[1, 2, 3, 4, 5]

In [42]:
l[3:]

[4, 5]

In [22]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
a.ndim

2

In [24]:
a.shape

(3, 4)

In [25]:
a.size

12

In [26]:
a.dtype

dtype('int64')

In [27]:
a.itemsize

8

### Срезы

In [28]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
a[0]

array([1, 2, 3, 4])

In [30]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [31]:
b[0]

array([[1, 2],
       [3, 4]])

In [32]:
a[:,2]

array([ 3,  7, 11])

In [36]:
b[:,1]

array([[3, 4],
       [7, 8]])

In [37]:
b[0,1]

array([3, 4])

In [38]:
b[:, :, 1]

array([[2, 4],
       [6, 8]])

In [39]:
a[0, 1]

np.int64(2)

In [40]:
b[0, 1, 1]

np.int64(4)

In [41]:
a[0,1]= 10
a

array([[ 1, 10,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
a[:2]

array([[ 1, 10,  3,  4],
       [ 5,  6,  7,  8]])

In [43]:
a[:2, 2:]

array([[3, 4],
       [7, 8]])

In [44]:
a[:2, 3]

array([4, 8])

In [45]:
a[-1:, -3:-1]

array([[10, 11]])

### Арифметические операции

#### 1D массивы

In [46]:
a = np.array([20,30,40,50])
b = np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [47]:
a + b

array([20, 31, 42, 53])

In [48]:
a - b

array([20, 29, 38, 47])

In [49]:
a * b

array([  0,  30,  80, 150])

In [50]:
 b / a

array([0.        , 0.03333333, 0.05      , 0.06      ])

In [51]:
b ** 2

array([0, 1, 4, 9])

In [52]:
10 * np.sqrt(a)

array([44.72135955, 54.77225575, 63.2455532 , 70.71067812])

In [53]:
a < 35

array([ True,  True, False, False])

In [54]:
# Срез по логическому выражению
a[a < 35]

array([20, 30])

In [55]:
b[b%2 == 0]

array([0, 2])

In [56]:
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
c[c%2 == 0]

array([2, 4, 6, 8])

#### 2D массивы

In [57]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])
print(A)
print(B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


In [58]:
A + B

array([[3, 1],
       [3, 5]])

In [59]:
A - B

array([[-1,  1],
       [-3, -3]])

In [60]:
A * B

array([[2, 0],
       [0, 4]])

In [61]:
A / B

C:\Users\D\AppData\Local\Temp\ipykernel_12940\3006334257.py:1: RuntimeWarning: divide by zero encountered in divide
  A / B


array([[0.5 ,  inf],
       [0.  , 0.25]])

In [62]:
A @ B

array([[5, 4],
       [3, 4]])

In [63]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [64]:
C = np.array([[1,1,1], [0,1,2]])
D = np.array([[2,0,1], [3,4,5]])
print(C)
print(D)

[[1 1 1]
 [0 1 2]]
[[2 0 1]
 [3 4 5]]


In [65]:
C * D

array([[ 2,  0,  1],
       [ 0,  4, 10]])

In [66]:
C @ D

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [67]:
D.T

array([[2, 3],
       [0, 4],
       [1, 5]])

In [68]:
C @ D.T

array([[ 3, 12],
       [ 2, 14]])

In [69]:
C.T @ D

array([[ 2,  0,  1],
       [ 5,  4,  6],
       [ 8,  8, 11]])

### Методы агрегирования

In [70]:
D.min()

np.int64(0)

In [71]:
D.max()

np.int64(5)

In [72]:
D.sum()

np.int64(15)

In [73]:
D.mean()

np.float64(2.5)

In [74]:
D.prod()

np.int64(0)

In [75]:
D.var()

np.float64(2.9166666666666665)

In [76]:
D.std()

np.float64(1.707825127659933)

In [77]:
D

array([[2, 0, 1],
       [3, 4, 5]])

In [78]:
D.sum(axis = 0)

array([5, 4, 6])

In [79]:
D.sum(axis = 1)

array([ 3, 12])

In [80]:
D.mean(axis = 0)

array([2.5, 2. , 3. ])

In [81]:
D.mean(axis = 1)

array([1., 4.])

### Случайные числа

In [82]:
np.random.default_rng(42).random([3,2])

array([[0.77395605, 0.43887844],
       [0.85859792, 0.69736803],
       [0.09417735, 0.97562235]])

In [83]:
from numpy.random import default_rng

In [84]:
default_rng(42).random([2,3])

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

In [85]:
default_rng(42).random([2,3,2])

array([[[0.77395605, 0.43887844],
        [0.85859792, 0.69736803],
        [0.09417735, 0.97562235]],

       [[0.7611397 , 0.78606431],
        [0.12811363, 0.45038594],
        [0.37079802, 0.92676499]]])

In [86]:
default_rng(12).random([2,3])

array([[0.25082446, 0.94675294, 0.18932038],
       [0.17929141, 0.34988924, 0.23054125]])

### Изменение формы массива

In [95]:
a = np.floor(10*default_rng(42).random([3,4]))
a

array([[7., 4., 8., 6.],
       [0., 9., 7., 7.],
       [1., 4., 3., 9.]])

In [96]:
a.shape

(3, 4)

In [97]:
a.ravel()

array([7., 4., 8., 6., 0., 9., 7., 7., 1., 4., 3., 9.])

In [98]:
a.reshape(6,2)

array([[7., 4.],
       [8., 6.],
       [0., 9.],
       [7., 7.],
       [1., 4.],
       [3., 9.]])

In [99]:
a.reshape(2, 3, 2)

array([[[7., 4.],
        [8., 6.],
        [0., 9.]],

       [[7., 7.],
        [1., 4.],
        [3., 9.]]])

### Объединение массивов

In [100]:
a = np.floor(10*default_rng(42).random([2,2]))
a

array([[7., 4.],
       [8., 6.]])

In [101]:
b = np.floor(10*default_rng(40).random([2,2]))
b

array([[7., 6.],
       [9., 0.]])

In [102]:
np.vstack([a,b])

array([[7., 4.],
       [8., 6.],
       [7., 6.],
       [9., 0.]])

In [103]:
np.hstack([a,b])

array([[7., 4., 7., 6.],
       [8., 6., 9., 0.]])

### Копирование

In [104]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [105]:
b = a

In [106]:
b is a

True

In [107]:
b[1,1] = 10
a

array([[ 1,  2,  3,  4],
       [ 5, 10,  7,  8],
       [ 9, 10, 11, 12]])

In [108]:
c = a.view()
c is a

False

In [109]:
c[1,1] = 999
a

array([[  1,   2,   3,   4],
       [  5, 999,   7,   8],
       [  9,  10,  11,  12]])

In [110]:
d = a.copy()
d is a

False

In [111]:
d[1,1] = 1000
a

array([[  1,   2,   3,   4],
       [  5, 999,   7,   8],
       [  9,  10,  11,  12]])

In [112]:
d

array([[   1,    2,    3,    4],
       [   5, 1000,    7,    8],
       [   9,   10,   11,   12]])

In [113]:
a1 = [1,2,3,4,5]
b1 = a1
b1[1] = False

In [118]:
a1 = 1

In [119]:
b1

[1, False, 3, 4, 5]

In [120]:
a1

1